### ISSUE TITLE
crates.io links to wrong documentation

### ISSUE THREAD

**Issue by mistydemeo** [ndesh26/evdev-rs#64]
The [`crates.io` page](https://crates.io/crates/evdev-rs) links to the wrong documentation page. It currently goes to [this page](http://ndesh26.github.io/evdev-rs) on your GitHub subdomain, which looks like it comes from before the 0.5.0 refactor and has the wrong API for the current vresion of `evdev-rs`. Would the [docs.rs](https://docs.rs/evdev-rs/) page be the right one?

**Comment by ndesh26** [comment]
Thanks for bringing it to my notice. 
I think it is best to leave the documentation field [empty](https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field) and crates.io will automatically pick the correct docs.rs link. I will update it in the next release. As a temporary solution, I will push the latest docs to my subdomain so that people are directed to the right documentation.

**Comment by ndesh26** [comment]
I have Cargo.toml as mentioned in the previous commit. It will be reflected with the new release.
