### ISSUE TITLE
Fix documentation for 0.6.0

### ISSUE THREAD

**Issue by dhalucario** [ndesh26/evdev-rs#98]
The current documentation is broken.
https://docs.rs/crate/evdev-rs/0.6.0

**Comment by ndesh26** [comment]
I will check out the build fail

**Comment by ndesh26** [comment]
It's happening because we have enabled libevdev-1-10 feature by default which requires libevdev>=1.10. However the docs.rs has libevdev 1.9.0 installed and in this scenario when the system libevdev version is older, we just panic and quit the build. The intention behind this was to not surprise the user and disabling the libevdev-1-10 feature. We can modify this behavior but the docs.rs documentation says that we are not allowed to access the internet. I am not sure if a git clone will be possible in this case. I will look into it more.

**Comment by ndesh26** [comment]
I have currently updated the readme with a [link](https://ndesh26.github.io/evdev-rs/evdev_rs/) to documentation hosted through github. It can be used until the issue with docs.rs is resolved. Unfortunately, crates.io will keep showing the old readme without the documentation link.

**Comment by maxbla** [comment]
Docs.rs uses Ubuntu 20 to build docs. Ubuntu 20 [currently has libevdev 1.9](https://packages.ubuntu.com/search?keywords=evdev&searchon=names&suite=focal&section=all). I don't think Ubuntu 20 will get libevdev 1.10, so we have to wait for docs.rs to update to a newer version of Ubuntu. I think it may have been a mistake to make the `libevdev-1-10` feature default; it would be nice to have the docs hosted on docs.rs. Also I'm leaving this link for how to add dependencies to the docs.rs build environment because it links to other relevant stuff https://forge.rust-lang.org/docs-rs/add-dependencies.html

**Comment by ndesh26** [comment]
> Docs.rs uses Ubuntu 20 to build docs. Ubuntu 20 [currently has libevdev 1.9](https://packages.ubuntu.com/search?keywords=evdev&searchon=names&suite=focal&section=all). I don't think Ubuntu 20 will get libevdev 1.10, so we have to wait for docs.rs to update to a newer version of Ubuntu. I think it may have been a mistake to make the `libevdev-1-10` feature default; it would be nice to have the docs hosted on docs.rs. Also I'm leaving this link for how to add dependencies to the docs.rs build environment because it links to other relevant stuff https://forge.rust-lang.org/docs-rs/add-dependencies.html

I agree. Let's disable the libevdev-1-10 feature by default. I am traveling right now, will look into it next week.
